import type { Metadata } from "next";
import { Geist, Geist_Mono, Black_Ops_One} from "next/font/google";
import "./globals.css";


const blackOps = Black_Ops_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-blackops',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Syauqi Portofolio",
  description: "Generated by create next app",
  icons: "/foto.png"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${blackOps.variable} antialiased`}>
        {children}
      </body>
    </html>
    
  );
}
